env:
  dev_test
Rule:
  version:
    1.0.0
  author:
    smicro
  swtich:
    on
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?characterEncoding=utf8&useUnicode=true&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: smicro
    password: smicro
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
